services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfCrawler\Crawler\:
    resource: '../Classes/*'

  dashboard.widget.typo3_crawler_widget.queuesize:
    class: 'FriendsOfCrawler\Crawler\Widgets\QueueSizeWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@FriendsOfCrawler\Crawler\Widgets\Provider\QueueSizeDataProvider'
      $options:
        title: 'LLL:EXT:typo3_crawler_widget/Resources/Private/Language/locallang.xlf:dashboard.widget.queuesize.title'
        icon: 'apps-toolbar-menu-search'
    tags:
      - name: dashboard.widget
        identifier: 'crawler.queuesize'
        groupNames: 'crawler'
        title: 'LLL:EXT:typo3_crawler_widget/Resources/Private/Language/locallang.xlf:dashboard.widget.queuesize.widget.title'
        description: 'LLL:EXT:typo3_crawler_widget/Resources/Private/Language/locallang.xlf:dashboard.widget.queuesize.description'
        iconIdentifier: 'content-widget-number'
        height: 'small'
        width: 'small'